- https://cpp-learning.com/pytorch-geometric/

In [1]:
import torch
from torch_geometric.data import Data

In [2]:
# ノード
src = [0, 1, 2]  # 送信側
dst = [1, 2, 1]  # 受信側

# エッジ
edge_index = torch.tensor([src, dst], dtype=torch.long)

# ノードの特徴量
x0 = [1, 2]
x1 = [3, 4]
x2 = [5, 6]
x = torch.tensor([x0, x1, x2], dtype=torch.float)

# ラベル
y0 = [1]
y1 = [0]
y2 = [1]
y = torch.tensor([y0, y1, y2], dtype=torch.float)

data = Data(x=x, y=y, edge_index=edge_index)


In [3]:
def check_graph(data):
    '''グラフ情報を表示'''
    print("グラフ構造:", data)
    print("グラフのキー: ", data.keys)
    print("ノード数:", data.num_nodes)
    print("エッジ数:", data.num_edges)
    print("ノードの特徴量数:", data.num_node_features)
    print("孤立したノードの有無:", data.contains_isolated_nodes())
    print("自己ループの有無:", data.contains_self_loops())
    print("====== ノードの特徴量:x ======")
    print(data['x'])
    print("====== ノードのクラス:y ======")
    print(data['y'])
    print("========= エッジ形状 =========")
    print(data['edge_index'])

In [4]:
check_graph(data)

グラフ構造: Data(x=[3, 2], edge_index=[2, 3], y=[3, 1])
グラフのキー:  ['x', 'edge_index', 'y']
ノード数: 3
エッジ数: 3
ノードの特徴量数: 2
孤立したノードの有無: False
自己ループの有無: False
====== ノードの特徴量:x ======
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
====== ノードのクラス:y ======
tensor([[1.],
        [0.],
        [1.]])
========= エッジ形状 =========
tensor([[0, 1, 2],
        [1, 2, 1]])


/Users/WatanabeShingo/opt/anaconda3/lib/python3.9/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'contains_isolated_nodes' is deprecated, use 'has_isolated_nodes' instead
  warnings.warn(out)
/Users/WatanabeShingo/opt/anaconda3/lib/python3.9/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'contains_self_loops' is deprecated, use 'has_self_loops' instead
  warnings.warn(out)
